---
  # 
- name: set trunk port
  ios_config:
    provider: "{{ provider }}"
    lines:
    - switchport trunk encap dot1q
    - switchport mode trunk
    - switchport trunk allowed vlan none
    parents: interface range {{ item.range }}
  with_items: "{{ ports[ansible_hostname] }}"
  # 
- name: set trunk allowed
  ios_config:
    provider: "{{ provider }}"
    lines:
    - switchport trunk allowed vlan add {{ item.1 }}
    parents: interface range {{ item.0.range }}
  with_subelements: 
  - "{{ ports[ansible_hostname] }}"
  - allowed
  # 
- name: no shut
  ios_config:
    provider: "{{ provider }}"
    lines:
    - no shutdown
    parents: interface range {{ item.range }}
  with_items: "{{ ports[ansible_hostname] }}"

- pause: seconds=15
